# Generated by Django 3.2.18 on 2026-08-29 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0002_gameweekresult_last_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_number', models.IntegerField(help_text='Newspaper Issue # (typically matches GW number)', unique=True)),
                ('headline', models.CharField(default='THE WEEKLY FPL MASSACRE', max_length=255)),
                ('subheadline', models.CharField(blank=True, default='', max_length=300)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chief_editor', models.CharField(default='The League Scribe & Hater-in-Chief', max_length=120)),
                ('weather_report', models.CharField(default='High pressure in the relegation zone, 100% chance of tears.', max_length=200)),
                ('editorial_lead', models.TextField(help_text='Front-page main editorial breakdown of the gameweek')),
                ('clown_reason', models.TextField(blank=True, default='')),
                ('king_reason', models.TextField(blank=True, default='')),
                ('quote_of_the_week', models.TextField(blank=True, default='')),
                ('quote_author', models.CharField(blank=True, default='Anonymous Benchwarmer', max_length=120)),
                ('defaulter_roast', models.TextField(blank=True, default='', help_text='Roast dedicated to unpaid or late contributors')),
                ('transfer_hit_roast', models.TextField(blank=True, default='', help_text='Roast for reckless -4 hits or bench blunders')),
                ('classified_ads_raw', models.TextField(blank=True, default='[]', help_text='JSON encoded list of satirical classified ads')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clown_of_the_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clown_editions', to='league.member')),
                ('gameweek', models.OneToOneField(help_text='Associated gameweek for this newspaper edition', on_delete=django.db.models.deletion.CASCADE, related_name='roast_edition', to='league.gameweek')),
                ('king_of_the_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='king_editions', to='league.member')),
            ],
            options={
                'verbose_name': 'Gazette Edition',
                'verbose_name_plural': 'Gazette Editions',
                'ordering': ['-edition_number'],
            },
        ),
        migrations.CreateModel(
            name='ManagerRoastItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_in_gw', models.IntegerField(default=1)),
                ('net_points', models.IntegerField(default=0)),
                ('badge', models.CharField(default='MID-TABLE', max_length=50)),
                ('roast_title', models.CharField(max_length=255)),
                ('roast_body', models.TextField()),
                ('verdict', models.CharField(default='Verdict: Needs divine intervention', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_roasts', to='news.roastedition')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_roasts', to='league.member')),
            ],
            options={
                'verbose_name': 'Manager Roast',
                'verbose_name_plural': 'Manager Roasts',
                'ordering': ['rank_in_gw', 'order'],
            },
        ),
    ]
