# Generated by Django 3.2.18 on 2026-08-28 13:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('deadline_time', models.DateTimeField(help_text='Official FPL Gameweek deadline (UTC)')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('finished', 'Finished')], default='upcoming', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('is_next', models.BooleanField(default=False)),
                ('month', models.IntegerField(default=8, help_text='Month number 1-12 for monthly filters')),
                ('season', models.CharField(default='2026/27', max_length=20)),
                ('payout_calculated', models.BooleanField(default=False)),
                ('prize_pool_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Gameweek',
                'verbose_name_plural': 'Gameweeks',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_entry_id', models.IntegerField(help_text='FPL team entry ID', unique=True)),
                ('team_name', models.CharField(max_length=120)),
                ('manager_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Phone number for M-Pesa / reminders (e.g., 254712345678)', max_length=20)),
                ('avatar_url', models.CharField(blank=True, max_length=400, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['manager_name'],
            },
        ),
        migrations.CreateModel(
            name='GameweekResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_points', models.IntegerField(default=0, help_text='Gross GW points before hits')),
                ('transfer_cost', models.IntegerField(default=0, help_text='Transfer cost points deduction')),
                ('net_points', models.IntegerField(default=0, help_text='Net GW points = gw_points - transfer_cost')),
                ('overall_rank', models.IntegerField(default=0, help_text='FPL Global Overall Rank')),
                ('league_rank', models.IntegerField(default=0, help_text='Rank within FPL Boys mini-league for this GW')),
                ('gw_prize_won', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prize won for top 3 finish in this GW', max_digits=10)),
                ('is_top3', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='league.gameweek')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gw_results', to='league.member')),
            ],
            options={
                'verbose_name': 'Gameweek Result',
                'verbose_name_plural': 'Gameweek Results',
                'ordering': ['gameweek', 'league_rank', '-net_points'],
                'unique_together': {('member', 'gameweek')},
            },
        ),
    ]
