# Generated by Django 3.2.18 on 2026-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweekresult',
            name='last_rank',
            field=models.IntegerField(default=0, help_text='Rank in previous gameweek for tracker arrow'),
        ),
    ]
