# Generated by Django 3.2.18 on 2026-08-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_gameweekresult_last_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_gameweek',
            field=models.IntegerField(default=1, help_text='Gameweek number when the member joined the league'),
        ),
    ]
