# Generated by Django 3.2.18 on 2026-09-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_set_aron_gw1_pardon_and_zero_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweek',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('finalizing', 'Finalizing Bonuses'), ('finished', 'Finished')], default='upcoming', max_length=20),
        ),
    ]
