# Generated by Django 3.2.18 on 2026-08-28 13:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PAYMENT_CREATED', 'Payment Created'), ('PAYMENT_UPDATED', 'Payment Updated'), ('PAYMENT_DELETED', 'Payment Deleted'), ('REMINDER_GENERATED', 'Reminder Generated'), ('FPL_SYNC', 'FPL Sync Performed'), ('PAYOUT_CALCULATED', 'Payout Calculated')], max_length=50)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(default='System / Treasurer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='Amount paid in Ksh.', max_digits=10)),
                ('timestamp_received', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when M-Pesa payment was received')),
                ('mpesa_code', models.CharField(blank=True, help_text='M-Pesa transaction reference (e.g. QJH78291KL)', max_length=50, null=True)),
                ('verified', models.BooleanField(default=True, help_text='Whether this payment has been verified by the treasurer')),
                ('is_late', models.BooleanField(default=False, help_text='Automatically set to True if received after the official GW deadline')),
                ('late_fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late fine assessed (routed into BBQ Pot, typically Ksh. 50)', max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='league.gameweek')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='league.member')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-timestamp_received', '-gameweek__number'],
                'unique_together': {('member', 'gameweek')},
            },
        ),
    ]
