# Generated by Django 3.2.18 on 2026-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_password_hash', models.CharField(default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Treasury Configuration',
                'verbose_name_plural': 'Treasury Configuration',
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('PAYMENT_CREATED', 'Payment Created'), ('PAYMENT_UPDATED', 'Payment Updated'), ('PAYMENT_DELETED', 'Payment Deleted'), ('REMINDER_GENERATED', 'Reminder Generated'), ('FPL_SYNC', 'FPL Sync Performed'), ('PAYOUT_CALCULATED', 'Payout Calculated'), ('TREASURY_UNLOCKED', 'Treasury Unlocked with Admin Password')], max_length=50),
        ),
    ]
