# Generated by Django 3.2.18 on 2026-08-28 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_gameweekresult_last_rank'),
        ('treasury', '0002_auto_20260828_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('PAYMENT_CREATED', 'Payment Created'), ('PAYMENT_UPDATED', 'Payment Updated'), ('PAYMENT_DELETED', 'Payment Deleted'), ('PRIZE_DISBURSED', 'Prize Disbursed via M-Pesa'), ('REMINDER_GENERATED', 'Reminder Generated'), ('FPL_SYNC', 'FPL Sync Performed'), ('PAYOUT_CALCULATED', 'Payout Calculated'), ('TREASURY_UNLOCKED', 'Treasury Unlocked with Admin Password')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_late',
            field=models.BooleanField(default=False, help_text='Automatically set to True if received after the official GW deadline (except waived GWs)'),
        ),
        migrations.CreateModel(
            name='PrizePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount disbursed in Ksh.', max_digits=10)),
                ('payout_method', models.CharField(choices=[('MPESA_CASH', 'M-Pesa Cash Disbursal'), ('REINVESTED', 'Reinvested in Future GWs')], default='MPESA_CASH', max_length=20)),
                ('mpesa_reference', models.CharField(blank=True, help_text='Outgoing M-Pesa Transaction Ref (e.g. QLK983021LK)', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('disbursed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gameweek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_payouts', to='league.gameweek')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_payouts', to='league.member')),
            ],
            options={
                'verbose_name': 'Prize Payout',
                'verbose_name_plural': 'Prize Payouts',
                'ordering': ['-disbursed_at'],
            },
        ),
    ]
