# Generated by Django 3.2.18 on 2026-09-01 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_set_aron_gw1_pardon_and_zero_points'),
        ('treasury', '0003_auto_20260828_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount received in Ksh.', max_digits=10)),
                ('mpesa_code', models.CharField(blank=True, help_text='M-Pesa Transaction Code (e.g. QJH78291KL)', max_length=50, null=True)),
                ('timestamp_received', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when payment was received')),
                ('transaction_type', models.CharField(choices=[('MPESA', 'M-Pesa Cash Payment'), ('PRIZE_ROLLOVER', 'Prize Rollover Conversion'), ('MANUAL', 'Manual Adjustment')], default='MPESA', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='league.member')),
                ('starting_gameweek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_transactions', to='league.gameweek')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-timestamp_received', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Parent M-Pesa transaction this allocation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='treasury.paymenttransaction'),
        ),
    ]
