# Generated by Django 3.2.18 on 2026-09-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_auto_20260901_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fine_paid',
            field=models.BooleanField(default=False, help_text='Whether the late fine (Ksh. 50) has been paid/settled by the member'),
        ),
    ]
