# Generated by Django 3.2.18 on 2026-09-18 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_payment_fine_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizepayout',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Parent transaction if this payout was reinvested', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_payouts', to='treasury.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Parent M-Pesa transaction this allocation belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='treasury.paymenttransaction'),
        ),
        migrations.CreateModel(
            name='TransactionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated from this transaction to this payment in Ksh.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(help_text='Target Gameweek payment record', on_delete=django.db.models.deletion.CASCADE, related_name='allocation_records', to='treasury.payment')),
                ('transaction', models.ForeignKey(help_text='Parent payment transaction', on_delete=django.db.models.deletion.CASCADE, related_name='allocation_records', to='treasury.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Transaction Allocation',
                'verbose_name_plural': 'Transaction Allocations',
                'ordering': ['created_at'],
            },
        ),
    ]
