# Generated by Django 3.2.18 on 2026-09-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0007_backfill_transaction_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionallocation',
            name='allocation_type',
            field=models.CharField(choices=[('CONTRIBUTION', 'Gameweek Contribution'), ('LATE_FINE', 'Late Fine Settlement')], default='CONTRIBUTION', help_text='Whether this allocation covers the base GW contribution or a late fine', max_length=20),
        ),
    ]
